config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home', as: 'home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.haml
%footer.footer-3
  .container
    .row
      .col-md-6.text-center.text-md-left.mt-2.mb-3.pt-1
        %p
          Copyright © Dogtor
          %i.fa.fa-paw{"aria-hidden" => "true"}
          = ". All rights reserved."
      .col-md-6.text-center.text-md-right.mt-2.mb-3.pt-1
        %p
          Layout by
          = link_to 'medialoot.com', 'https://medialoot.com/'

app/views/layouts/_messages.haml
- if notice.present?
  %p.notice= notice
- if alert.present?
  %p.alert= alert

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-custom.navbar-light.fixed-top
  .container
    = link_to home_path, { class: "navbar-brand mx-auto" } do
      Dogtor
      %i.fa.fa-paw{"aria-hidden" => "true"}
    %button.navbar-toggler{"aria-controls" => "navbarToggler-5", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarToggler-5", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarToggler-5.collapse.navbar-collapse.justify-content-end
      %ul.navbar-nav.mt-2.mt-md-0
        %li.nav-item{ class: ("active" if current_page?(home_path))}
          = link_to home_path, { class: "nav-link" } do
            Home
            - if current_page?(home_path)
              %span.sr-only (current)
        %li.nav-item{ class: ("active" if current_page?(about_path))}
          = link_to about_path, { class: "nav-link" } do
            About
        %li.nav-item{ class: ("active" if current_page?(contact_path))}
          = link_to contact_path, { class: "nav-link" } do
            Contact
        %li.nav-item
          %a.btn.btn-outline-success.btn-outline{:href => "#"} Buy Now

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dogtor
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.png'
  %body
    .text-center
      = render 'layouts/messages'
      = render 'layouts/navbar'
      = yield
      = render 'layouts/footer'

app/views/static_pages/about.html.haml
.container
  %h2 Meet our Team
  %p.lead Programmers and pets enthusiasts
  .divider
  .row
    .col-md-4.col-team
      %img.rounded-corners.img-fluid{:height => "240", :src => "images/team-1.jpg", :width => "240"}/
      %h4 Katarzyna Świątek
      %p
        %span.emphasis Designer
      %ul.social
        %li
          %a.fa.fa-linkedin{:href => "#", :title => "LinkedIn"}
        .clear
    .col-md-4.col-team
      %img.rounded-corners.img-fluid{:height => "240", :src => "images/team-2.jpg", :width => "240"}/
      %h4 Jędrzej Bryll
      %p
        %span.emphasis Designer
      %ul.social
        %li
          %a.fa.fa-linkedin{:href => "#", :title => "LinkedIn"}
        .clear
    .col-md-4.col-team
      %img.rounded-corners.img-fluid{:height => "240", :src => "images/team-3.jpg", :width => "240"}/
      %h4 Oliwia Michalak
      %p
        %span.emphasis Designer
      %ul.social
      %li
        %a.fa.fa-linkedin{:href => "#", :title => "LinkedIn"}
        .clear

app/views/static_pages/contact.haml
%p Contact

app/views/static_pages/contact.html.haml
%p Contact

app/views/static_pages/home.html.haml
%nav.navbar.navbar-toggleable-sm.navbar-custom.navbar-light
  .container
    %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarToggler-5", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarToggler-5", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    %a.navbar-brand{:href => "#"} Dogtor
    #navbarToggler-5.collapse.navbar-collapse.justify-content-end
      %ul.navbar-nav.mt-2.mt-md-0
        %li.nav-item.active
          %a.nav-link{:href => "#"}
            Home
            %span.sr-only (current)
        %li.nav-item
          %a.nav-link{:href => "#"} About
        %li.nav-item
          %a.nav-link{:href => "#"} Contact
        %li.nav-item
          %a.btn.btn-outline-success.btn-outline{:href => "#"} Register
.cover-container.pb-5
  .cover-inner.container
    %p.lead Take care of your pet today
    .divider
    %h1.jumbotron-heading
      Say
      %em hello
      to our
      %strong Dogtor
    .row
      .offset-md-4.col-md-4.mt-5
        %button.btn.btn-lg.btn-success.pill-btn{:type => "submit"} Get Started